services:
    franken_php:
        build:
            context: ./infra/
            dockerfile: ./frankenphp/Dockerfile
        volumes:
            - ./project:/app
        expose:
            - "80"
        environment:
            SERVER_NAME: "http://:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.group1.rule=Host(`group1.ehei.localhost`)"
            - "traefik.http.routers.group1.entrypoints=websecure"
            - "traefik.http.routers.group1.tls=true"
            - "traefik.http.services.group1.loadbalancer.server.port=80"
            - "traefik.http.services.group1.loadbalancer.server.scheme=http"
            - "traefik.docker.network=proxy-net"

        networks:
            - internal_network
            - proxy-net

    database:
        image: mysql
        platform: linux/x86_64
        command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app
        volumes:
            - group1_mysql:/var/lib/mysql:delegated
        networks:
            - internal_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        environment:
            PMA_HOST: database
        depends_on:
            - database
        networks:
            - internal_network
            - proxy-net
        volumes:
            - group1_db_admin_data:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.group1-pma.rule=Host(`pma.group1.ehei.localhost`)"
            - "traefik.http.routers.group1-pma.entrypoints=websecure"
            - "traefik.http.routers.group1-pma.tls=true"
            - "traefik.http.services.group1-pma.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy-net"

volumes:
    group1_db_admin_data:
        name: group1_db_admin_data
    group1_mysql:
        name: group1_mysql

networks:
    internal_network:
        name: internal_network_group1
    proxy-net:
        name: proxy-net
        external: true
